<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StructuralMember;

class StructuralMemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            // BPH (inti)
            [
                'name' => 'Muhammad Farhan Pratama',
                'role' => 'Ketua Himpunan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/M. FARHAN PRATAMAcrp.webp',
                'instagram' => 'https://www.instagram.com/frhnprtmaa_/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 1,
            ],
            [
                'name' => 'Muhammad Dava Prayoga',
                'role' => 'Wakil Ketua Himpunan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/M.DAVA PRAYOGAcrp.webp',
                'instagram' => 'https://www.instagram.com/davapryga/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 2,
            ],
            [
                'name' => 'Siti Nabila Zhafirah',
                'role' => 'Sekretaris Umum',
                'class' => 'MI 2024',
                'avatar' => '/anggota/SITI NABILA ZHAFIRAHcrp.webp',
                'instagram' => 'https://www.instagram.com/nabilazhafirh/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 3,
            ],
            [
                'name' => 'Eka Rahayu Putri',
                'role' => 'Wakil Sekretaris Umum',
                'class' => 'MI 2025',
                'avatar' => '/anggota/Eka Rahayu Putri (2).webp',
                'instagram' => 'https://www.instagram.com/ekarhyptr/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 4,
            ],
            [
                'name' => 'Muthia Maylafayza Inayah',
                'role' => 'Bendahara Umum',
                'class' => 'MI 2024',
                'avatar' => '/anggota/MUTIA MAYLAFAYZA INAYAHcrp.webp',
                'instagram' => 'https://www.instagram.com/muthiamaylaa/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 5,
            ],
            [
                'name' => 'Putri Afifah Khairunnisa',
                'role' => 'Wakil Bendahara Umum',
                'class' => 'MI 2025',
                'avatar' => '/anggota/Putri Afifah Khairunnisa (2).webp',
                'instagram' => 'https://www.instagram.com/put__t/',
                'department_id' => 'inti',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 6,
            ],

            // PTKP (ptkp)
            [
                'name' => 'Al Fajri Nur Ramadhan',
                'role' => 'Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/AL FAJRI NUR RAMADHAN.webp',
                'instagram' => 'https://www.instagram.com/fajriii._',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 7,
            ],
            [
                'name' => 'Agnes',
                'role' => 'Wakil Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/agnes.webp',
                'instagram' => 'https://www.instagram.com/lavienagn/',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 8,
            ],
            [
                'name' => 'Shofi Nanda Rismaliani',
                'role' => 'Sekretaris',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/SHOFI NANDA R.webp',
                'instagram' => 'https://www.instagram.com/shofinanda_/',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 9,
            ],
            [
                'name' => 'Lara Amelia Apriani',
                'role' => 'Bendahara',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/lara.webp',
                'instagram' => 'https://www.instagram.com/laraamelia_/',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 10,
            ],
            [
                'name' => 'Lenno Nardo',
                'role' => 'Koordinator Akademik',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/leno.webp',
                'instagram' => 'https://www.instagram.com/lenno_nar/',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 11,
            ],
            [
                'name' => 'Muhammad Ichwan',
                'role' => 'Koordinator Kepemudaan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/M.ICWHAN.webp',
                'instagram' => 'https://www.instagram.com/mhm.ichwnnn_/',
                'department_id' => 'ptkp',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 12,
            ],

            // PTKP Members (Akademik)
            [
                'name' => 'Devi Aprianti',
                'role' => 'Anggota',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/devi.webp',
                'instagram' => 'https://www.instagram.com/_deviafrnti/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 13,
            ],
            [
                'name' => 'M. Irfan Apriansyah',
                'role' => 'Anggota',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/M.IRFAN APRIANSYAH.webp',
                'instagram' => 'https://www.instagram.com/panzya/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 14,
            ],
            [
                'name' => 'Kemas Muhammad Amar Fauzan',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Kemas Amar.webp',
                'instagram' => 'https://www.instagram.com/kmsamarf_/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 15,
            ],
            [
                'name' => 'M. Bahrudin',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/M. Bahrudin.webp',
                'instagram' => 'https://www.instagram.com/m.bhrdnnn_/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 16,
            ],
            [
                'name' => 'Dimas Yuda Pratama',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Dimas Yuda Pratama (2).webp',
                'instagram' => 'https://www.instagram.com/dimytma.17/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 17,
            ],
            [
                'name' => 'Niken Septi Andini',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Niken S Andini (2).webp',
                'instagram' => 'https://www.instagram.com/nsandiny/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 18,
            ],
            [
                'name' => 'Delvia Apriani',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Delvia Apriani (2).webp',
                'instagram' => 'https://www.instagram.com/dlviaprini/',
                'department_id' => 'ptkp',
                'division_id' => 'akademik',
                'type' => 'member',
                'order_index' => 19,
            ],

            // PTKP Members (Kepemudaan)
            [
                'name' => 'Miftahul Jannah',
                'role' => 'Anggota',
                'class' => 'MI 2024',
                'avatar' => '/anggota/ptkp24/MIFTAHUL JANNAH-.webp',
                'instagram' => 'https://www.instagram.com/mitaeez_/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 20,
            ],
            [
                'name' => 'Briliana Azizah',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Briliana Azizah (2).webp',
                'instagram' => 'https://www.instagram.com/brlnaazzh/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 21,
            ],
            [
                'name' => 'Muhammad Fadlil',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Muhammad Fadlil (2).webp',
                'instagram' => 'https://www.instagram.com/koharuitsuka_/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 22,
            ],
            [
                'name' => 'Innayah Dwikhailah Putri',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Innayah DwiKhailah Putri (2).webp',
                'instagram' => 'https://www.instagram.com/nayyaaa.a_/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 23,
            ],
            [
                'name' => 'Irham Bagus Sanjaya',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/irham bagus sanjaya (2).webp',
                'instagram' => 'https://www.instagram.com/leoirham1/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 24,
            ],
            [
                'name' => 'Muhammad Satria Anugrah',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/Satria Anugrah.webp',
                'instagram' => 'https://www.instagram.com/rragaa__/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 25,
            ],
            [
                'name' => 'Rasya Ratu Juanna',
                'role' => 'Anggota',
                'class' => 'MI 2025',
                'avatar' => '/anggota/ptkp25/rasya ratu juanna (2).webp',
                'instagram' => 'https://www.instagram.com/rsyratuu/',
                'department_id' => 'ptkp',
                'division_id' => 'kepemudaan',
                'type' => 'member',
                'order_index' => 26,
            ],

            // HUMAS (humas)
            [
                'name' => 'Masya Dinar Fadillah',
                'role' => 'Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/MASYA DINAR.webp',
                'instagram' => 'https://www.instagram.com/msydnrfdllh/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 27,
            ],
            [
                'name' => 'Muhamad Rifky Septiansyah',
                'role' => 'Wakil Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/M. RIFKI SEPTIANSYAH.webp',
                'instagram' => 'https://www.instagram.com/fitch_579/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 28,
            ],
            [
                'name' => 'Panisah',
                'role' => 'Sekretaris',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/panisa.webp',
                'instagram' => 'https://www.instagram.com/paniishaa/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 29,
            ],
            [
                'name' => 'Ajeng Alieffiyah Safitri',
                'role' => 'Bendahara',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/AJENG.webp',
                'instagram' => 'https://www.instagram.com/aalieffiyah/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 30,
            ],
            [
                'name' => 'Zakira Surani',
                'role' => 'Koordinator Kominfo',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/ZAKIRA.webp',
                'instagram' => 'https://www.instagram.com/zakiraa_sr/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 31,
            ],
            [
                'name' => 'Vanessa Septia Putri',
                'role' => 'Koordinator Medkraf',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/VANESSA.webp',
                'instagram' => 'https://www.instagram.com/vanessaasp_/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 32,
            ],
            [
                'name' => 'Nailah Zhafirah Cahyalia Jaya',
                'role' => 'Koordinator Jurnalis',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/NAILAH.webp',
                'instagram' => 'https://www.instagram.com/_snzcj_/',
                'department_id' => 'humas',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 33,
            ],

            // HUMAS Members (Kominfo)
            [
                'name' => 'Arien Salsabilla Basurini',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/ARIEN.webp',
                'instagram' => 'https://www.instagram.com/ariensb_/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 34,
            ],
            [
                'name' => 'Nadi Kurniawan',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/NADI.webp',
                'instagram' => 'https://www.instagram.com/nadikurniawan_/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 35,
            ],
            [
                'name' => 'Fajar Setyanusa',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Fajar Setyanusa (2).webp',
                'instagram' => 'https://www.instagram.com/adawn_n/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 36,
            ],
            [
                'name' => 'Nafi Julian Syam Fajri',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Nafi Julian Syam Fajri (2).webp',
                'instagram' => 'https://www.instagram.com/_nafijulian/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 37,
            ],
            [
                'name' => 'Diana Mareta',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Diana Mareta (2).webp',
                'instagram' => 'https://www.instagram.com/_aattaaa/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 38,
            ],
            [
                'name' => 'Anggun Ayu Tria Rahmah',
                'role' => 'Anggota Kominfo',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Anggun Ayu Tria Rahmah (2).webp',
                'instagram' => 'https://www.instagram.com/anggunayutriaa/',
                'department_id' => 'humas',
                'division_id' => 'kominfo',
                'type' => 'member',
                'order_index' => 39,
            ],

            // HUMAS Members (Medkraf)
            [
                'name' => 'Muhammad Nabil Akmal',
                'role' => 'Anggota Medkraf',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/naabil (2).webp',
                'instagram' => null,
                'department_id' => 'humas',
                'division_id' => 'medkraf',
                'type' => 'member',
                'order_index' => 40,
            ],
            [
                'name' => 'Finolia Rama Danti',
                'role' => 'Anggota Medkraf',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Finolia Rama Danti (2).webp',
                'instagram' => 'https://www.instagram.com/finnn0_0/',
                'department_id' => 'humas',
                'division_id' => 'medkraf',
                'type' => 'member',
                'order_index' => 41,
            ],
            [
                'name' => 'Nuril Maghfiroh',
                'role' => 'Anggota Medkraf',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Nuril Maghfiroh (2).webp',
                'instagram' => 'https://www.instagram.com/nuril_mghkamil02/',
                'department_id' => 'humas',
                'division_id' => 'medkraf',
                'type' => 'member',
                'order_index' => 42,
            ],
            [
                'name' => 'Helza Framesha',
                'role' => 'Anggota Medkraf',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/HelzaFramesha (2).webp',
                'instagram' => 'https://www.instagram.com/zeshakun_/',
                'department_id' => 'humas',
                'division_id' => 'medkraf',
                'type' => 'member',
                'order_index' => 43,
            ],
            [
                'name' => 'Thomas Kristalio Ariflan Santos',
                'role' => 'Anggota Medkraf',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Thomas Kristalio (2).webp',
                'instagram' => 'https://www.instagram.com/thomas6kasp/',
                'department_id' => 'humas',
                'division_id' => 'medkraf',
                'type' => 'member',
                'order_index' => 44,
            ],

            // HUMAS Members (Jurnalis)
            [
                'name' => 'Regas Sonjaya',
                'role' => 'Anggota Jurnalis',
                'class' => 'MI 2024',
                'avatar' => '/anggota/humas24/REGAS.webp',
                'instagram' => 'https://www.instagram.com/regasss._/',
                'department_id' => 'humas',
                'division_id' => 'jurnalis',
                'type' => 'member',
                'order_index' => 45,
            ],
            [
                'name' => 'Sulthan Muhammad Diftha Annashira',
                'role' => 'Anggota Jurnalis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/sultan.webp',
                'instagram' => 'https://www.instagram.com/sulthan.difthaa/',
                'department_id' => 'humas',
                'division_id' => 'jurnalis',
                'type' => 'member',
                'order_index' => 46,
            ],
            [
                'name' => 'Arau Imanuel Siritoitet',
                'role' => 'Anggota Jurnalis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Arau Imanuel Siritoitet (2).webp',
                'instagram' => 'https://www.instagram.com/arauimanuell/',
                'department_id' => 'humas',
                'division_id' => 'jurnalis',
                'type' => 'member',
                'order_index' => 47,
            ],
            [
                'name' => 'Muhammad Kevin Fadhilah Akmal',
                'role' => 'Anggota Jurnalis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/humas25/Muhammad Kevin F.A (2).webp',
                'instagram' => 'https://www.instagram.com/vynn.flx/',
                'department_id' => 'humas',
                'division_id' => 'jurnalis',
                'type' => 'member',
                'order_index' => 48,
            ],

            // PSDM (psdm)
            [
                'name' => 'Muhammad Naufal Athallah',
                'role' => 'Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/M.NAUFAL.webp',
                'instagram' => 'https://www.instagram.com/_aathallaah/',
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 49,
            ],
            [
                'name' => 'Aulia Niputri',
                'role' => 'Wakil Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/AULIA.webp',
                'instagram' => 'https://www.instagram.com/auliaaa_npt/',
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 50,
            ],
            [
                'name' => 'Sri Rahayu Rezeki',
                'role' => 'Sekretaris',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/SRI RAHAYU.webp',
                'instagram' => null,
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 51,
            ],
            [
                'name' => 'Shoofiyah Maharani',
                'role' => 'Bendahara',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/SHOOFIYAH.webp',
                'instagram' => 'https://www.instagram.com/shoofiyah_maharani/',
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 52,
            ],
            [
                'name' => 'Handika Putra',
                'role' => 'Koordinator Minat Bakat',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/HANDIKA.webp',
                'instagram' => 'https://www.instagram.com/hndkptr_/',
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 53,
            ],
            [
                'name' => 'Koordinator Bidang HRD',
                'role' => 'Koordinator Bidang HRD PSDM',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/anonym.webp',
                'instagram' => null,
                'department_id' => 'psdm',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 54,
            ],

            // PSDM Members (Minat Bakat)
            [
                'name' => 'Swarnata Prayoga',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/SWARNATA.webp',
                'instagram' => 'https://www.instagram.com/swarnatta/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 55,
            ],
            [
                'name' => 'Nurhaliza',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/HALIZA.webp',
                'instagram' => 'https://www.instagram.com/rlizaa_/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 56,
            ],
            [
                'name' => 'Nanda Meylani Putri',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/NANDA MELYANI.webp',
                'instagram' => null,
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 57,
            ],
            [
                'name' => 'Ridho Dwi Restiandi',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2024',
                'avatar' => '/anggota/psdm24/RIDHO DWI.webp',
                'instagram' => 'https://www.instagram.com/ridhdwir/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 58,
            ],
            [
                'name' => 'Muhammad Haekal Saleh',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Muhammad Haekal Saleh (2).webp',
                'instagram' => 'https://www.instagram.com/kallnm_/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 59,
            ],
            [
                'name' => 'Muhammad Fathir Romeo',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Fathir (2).webp',
                'instagram' => 'https://www.instagram.com/fthiromeo/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 60,
            ],
            [
                'name' => 'Shafia Aurajannah Marza',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/shafia_aurajannah_marza (2).webp',
                'instagram' => 'https://www.instagram.com/shafiaura/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 61,
            ],
            [
                'name' => 'Fika Dwi Jayanti',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Fika Dwi Jayanti (2).webp',
                'instagram' => 'https://www.instagram.com/fikadwijy/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 62,
            ],
            [
                'name' => 'Nurin Nabya',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Nurin Nabya.webp',
                'instagram' => 'https://www.instagram.com/nurinnabya/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 63,
            ],
            [
                'name' => 'Kayla Syakirah',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Kayla Syakirah (2).webp',
                'instagram' => 'https://www.instagram.com/kela_syakeerah/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 64,
            ],
            [
                'name' => 'M. Faizal Alfriandy',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Muhammad Faizal Alfriandy (2).webp',
                'instagram' => 'https://www.instagram.com/alfriqndy/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 65,
            ],
            [
                'name' => 'Muhammad Ridho Pratama',
                'role' => 'Anggota Minat Bakat',
                'class' => 'MI 2025',
                'avatar' => '/anggota/psdm25/Muhammad Ridho Pratama (2).webp',
                'instagram' => 'https://www.instagram.com/ridhopratamaapril/',
                'department_id' => 'psdm',
                'division_id' => 'minatbakat',
                'type' => 'member',
                'order_index' => 66,
            ],

            // KESMA (kesma)
            [
                'name' => 'Muhamad Rizqon Yasir',
                'role' => 'Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/M.RIZQON YASIR.webp',
                'instagram' => 'https://www.instagram.com/rizqonyasir/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 67,
            ],
            [
                'name' => 'Zalsabila Herawaty',
                'role' => 'Wakil Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/ZALSABILA HERAWATY.webp',
                'instagram' => 'https://www.instagram.com/zalsbila_/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 68,
            ],
            [
                'name' => 'Aisyah Arianti',
                'role' => 'Sekretaris',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/AISYAH ARIANTI.webp',
                'instagram' => 'https://www.instagram.com/aisyaharnt_/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 69,
            ],
            [
                'name' => 'Azzahra Dinda Febrianti',
                'role' => 'Bendahara',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/AZZAHRA DINDA FEBRIANTI.webp',
                'instagram' => 'https://www.instagram.com/zaraddn/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 70,
            ],
            [
                'name' => 'Muhammad Sutan Artha',
                'role' => 'Koordinator Agama',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/M.SUTAN ARTHA.webp',
                'instagram' => 'https://www.instagram.com/sutanart._/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 71,
            ],
            [
                'name' => 'Adhyaksa Micko Satria',
                'role' => 'Koordinator Sosial',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/ADHYAKSA MICKO SATRIA.webp',
                'instagram' => 'https://www.instagram.com/adhymicko_/',
                'department_id' => 'kesma',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 72,
            ],

            // KESMA Members (Agama)
            [
                'name' => 'Annisa Nurhidayah',
                'role' => 'Anggota Agama',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/ANNISA NURHIDAYAH.webp',
                'instagram' => 'https://www.instagram.com/niisaanrh/',
                'department_id' => 'kesma',
                'division_id' => 'agama',
                'type' => 'member',
                'order_index' => 73,
            ],
            [
                'name' => 'Muhammad Ghani Yusha',
                'role' => 'Anggota Agama',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/M. Ghani Yusha (2).webp',
                'instagram' => 'https://www.instagram.com/ghani.ys/',
                'department_id' => 'kesma',
                'division_id' => 'agama',
                'type' => 'member',
                'order_index' => 74,
            ],
            [
                'name' => 'Muhammad Rizky Pratama',
                'role' => 'Anggota Agama',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/M Rizky Pratama (2).webp',
                'instagram' => null,
                'department_id' => 'kesma',
                'division_id' => 'agama',
                'type' => 'member',
                'order_index' => 75,
            ],
            [
                'name' => 'Nabila Huwaida',
                'role' => 'Anggota Agama',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/Nabila Huwaida.webp',
                'instagram' => 'https://www.instagram.com/neabielaaa/',
                'department_id' => 'kesma',
                'division_id' => 'agama',
                'type' => 'member',
                'order_index' => 76,
            ],
            [
                'name' => 'Muhammad Rizki Wijaya',
                'role' => 'Anggota Agama',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/Rizky wijaya (2).webp',
                'instagram' => 'https://www.instagram.com/rzkiwjy/',
                'department_id' => 'kesma',
                'division_id' => 'agama',
                'type' => 'member',
                'order_index' => 77,
            ],

            // KESMA Members (Sosial)
            [
                'name' => 'Dimas Fajar Satrio',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/DIMAS FAJAR SATRIO.webp',
                'instagram' => 'https://www.instagram.com/dimas_f_s_/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 78,
            ],
            [
                'name' => 'Muhammad Rifki Surya Pratama',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/M.RIFKY.webp',
                'instagram' => null,
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 79,
            ],
            [
                'name' => 'Tarisha Bais Husna',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2024',
                'avatar' => '/anggota/kesma24/TARISHA BAIS HUSNA.webp',
                'instagram' => 'https://www.instagram.com/tarishabs/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 80,
            ],
            [
                'name' => 'Adinda Rahmalia',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/dinda (2).webp',
                'instagram' => 'https://www.instagram.com/ddindae_/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 81,
            ],
            [
                'name' => 'Amira Luthfia Alkamila',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/Amira Luthfia Alkamila_ (2).webp',
                'instagram' => 'https://www.instagram.com/mira_kmilaa/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 82,
            ],
            [
                'name' => 'Frans Ahmad Zharif',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/Frans Ahmad Zhariif (2).webp',
                'instagram' => 'https://www.instagram.com/franzhariif_/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 83,
            ],
            [
                'name' => 'Muhammad Rasya Syakir',
                'role' => 'Anggota Sosial',
                'class' => 'MI 2025',
                'avatar' => '/anggota/kesma25/Rasya Syakir.webp',
                'instagram' => 'https://www.instagram.com/mhmdrsya_s/',
                'department_id' => 'kesma',
                'division_id' => 'sosial',
                'type' => 'member',
                'order_index' => 84,
            ],

            // BISTRA (bistra)
            [
                'name' => 'Mochamad Raechan Albani',
                'role' => 'Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/RAECHAN ALBANI.webp',
                'instagram' => 'https://www.instagram.com/mochalbani_/',
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 85,
            ],
            [
                'name' => 'Rahmi Fauliza Hanapsari',
                'role' => 'Wakil Kepala Departemen',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/RAHMI FAULIZA HANAPSARI.webp',
                'instagram' => 'https://www.instagram.com/rahmifaulizaa/',
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 86,
            ],
            [
                'name' => 'Adellia Nurain',
                'role' => 'Sekretaris',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/ADELLIA NURAIN.webp',
                'instagram' => null,
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 87,
            ],
            [
                'name' => 'Liana Melisa',
                'role' => 'Bendahara',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/LIANA MELISA.webp',
                'instagram' => 'https://www.instagram.com/liaana05_/',
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 88,
            ],
            [
                'name' => 'Dani Maulana',
                'role' => 'Koordinator Bisnis',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/DANI MAULANA.webp',
                'instagram' => 'https://www.instagram.com/danii.mlna/',
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 89,
            ],
            [
                'name' => 'Natasya Bella Shavira',
                'role' => 'Koordinator Kemitraan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/NATASHA BELLA SHAVIRA.webp',
                'instagram' => 'https://www.instagram.com/natasya.bss/',
                'department_id' => 'bistra',
                'division_id' => null,
                'type' => 'head',
                'order_index' => 90,
            ],

            // BISTRA Members (Bisnis)
            [
                'name' => 'Tri Aji Alhuda',
                'role' => 'Anggota Bisnis',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/TRI AJI ALHUDA.webp',
                'instagram' => 'https://www.instagram.com/aji_alhd/',
                'department_id' => 'bistra',
                'division_id' => 'bisnis',
                'type' => 'member',
                'order_index' => 91,
            ],
            [
                'name' => 'Munzillin Zahri Aji',
                'role' => 'Anggota Bisnis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/munzilin zahri aji (2).webp',
                'instagram' => 'https://www.instagram.com/bukanmunjilin_/',
                'department_id' => 'bistra',
                'division_id' => 'bisnis',
                'type' => 'member',
                'order_index' => 92,
            ],
            [
                'name' => 'Muhammad Azrin',
                'role' => 'Anggota Bisnis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Muhammad Azrin.webp',
                'instagram' => 'https://www.instagram.com/_zrnnn07/',
                'department_id' => 'bistra',
                'division_id' => 'bisnis',
                'type' => 'member',
                'order_index' => 93,
            ],
            [
                'name' => 'Alfaris Abiyyu Ramadhan',
                'role' => 'Anggota Bisnis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Alfaris Abiyyu Ramadhan (2).webp',
                'instagram' => 'https://www.instagram.com/alfarisabiyyu.r_28/',
                'department_id' => 'bistra',
                'division_id' => 'bisnis',
                'type' => 'member',
                'order_index' => 94,
            ],
            [
                'name' => 'Fadhlan Lordiansyah',
                'role' => 'Anggota Bisnis',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Fadhlan lordiansyah (2).webp',
                'instagram' => 'https://www.instagram.com/flydoans_/',
                'department_id' => 'bistra',
                'division_id' => 'bisnis',
                'type' => 'member',
                'order_index' => 95,
            ],

            // BISTRA Members (Kemitraan)
            [
                'name' => 'Aldi Kurniawan',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/ALDI KURNIAWAN.webp',
                'instagram' => null,
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 96,
            ],
            [
                'name' => 'Sharla Imanda',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2024',
                'avatar' => '/anggota/bistra24/SHARLA IMANDA.webp',
                'instagram' => 'https://www.instagram.com/sharlamnd/',
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 97,
            ],
            [
                'name' => 'Afifah Saharani',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Afifah Saharani_ (2).webp',
                'instagram' => 'https://www.instagram.com/fifhshrnii_/',
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 98,
            ],
            [
                'name' => 'Fenita Harlina',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Fenita Harlina (2).webp',
                'instagram' => 'https://www.instagram.com/fnytahrlna_/',
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 99,
            ],
            [
                'name' => 'Ayu Sari Romadhon',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Ayu Sari Romadhon_ (2).webp',
                'instagram' => 'https://www.instagram.com/ayusr_ay/',
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 100,
            ],
            [
                'name' => 'Nabila Salsabila',
                'role' => 'Anggota Kemitraan',
                'class' => 'MI 2025',
                'avatar' => '/anggota/bistra25/Nabila.webp',
                'instagram' => 'https://www.instagram.com/nbilaslsbilla/',
                'department_id' => 'bistra',
                'division_id' => 'kemitraan',
                'type' => 'member',
                'order_index' => 101,
            ],
        ];

        foreach ($members as $member) {
            // Apply default styles to keep the current exact look or custom default rotation
            if ($member['type'] === 'head') {
                $member['image_rotation'] = 'rotate-3';
            } else {
                $member['image_rotation'] = 'rotate-0'; // members cards are generally flat or rotate-3 on hover
            }
            $member['image_grayscale'] = 'grayscale_hover';
            $member['image_object_position'] = 'object-center';
            $member['image_zoom'] = 'scale-100';

            StructuralMember::create($member);
        }
    }
}
